export const FETCH_INGREDIENTS='FETCH_INGREDIENTS'
export const ADD_INGREDIENTS='ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS='REMOVE_INGREDIENTS';

//Action Authentication
export const AUTH_START='AUTH_START'
export const AUTH_SUCCESS='AUTH_SUCCESS'
export const AUTH_FAIL='AUTH_FAIL'
export const AUTH_LOGOUT='AUTH_LOGOUT'

